theme: jekyll-theme-minimal
title: Shellder
description: Shellder reborn!
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  syntax_highlighter: rouge
